version: "3.7"

services:
  web:
    build: ./services/backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./services/backend:/usr/src/app
    ports:
      - 8002:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVICE=web-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=web_dev
      - POSTGRES_TEST_DB=web_test
    depends_on:
      - web-db
  web-db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  #We gonna add this later
  client:
    stdin_open: true
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - "./services/client:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_SERVICE_URL=http://localhost:8002 #//${REACT_APP_USERS_SERVICE_URL}
      #- CHOKIDAR_USEPOLLING=true
    depends_on:
      - web
